### ISSUE TITLE
kivy-garden garden bug (garden search fails)

### ISSUE THREAD

**Issue by jb1123** [kivy-garden/garden#24]
garden search installed in virtual environment fails. Fresh virtual environment, simple list of modules fails, no code on my side involved  so I believe it is an error in grden itself. Details:
<environment>
(venv) jb@jb-u16v1:~/python/meteread/bin$ pip list
appdirs (1.4.0)
buildozer (0.32)
colorama (0.3.7)
Cython (0.24.1)
Jinja2 (2.8)
Kivy (1.9.1)
Kivy-Garden (0.1.4)
MarkupSafe (0.23)
pexpect (4.2.1)
pip (8.1.2)
pkg-resources (0.0.0)
ptyprocess (0.5.1)
python-for-android (0.4)
requests (2.11.1)
setuptools (28.2.0)
sh (1.11)
six (1.10.0)
virtualenv (15.0.3)
wheel (0.30.0a0)

<command and output >
(venv) jb@jb-u16v1:~/python/meteread/bin$ garden search
[INFO   ] [Logger      ] Record log in /home/jb/.kivy/logs/kivy_16-10-03_1.txt
[INFO   ] [Kivy        ] v1.9.1
[INFO   ] [Python      ] v2.7.12 (default, Jul  1 2016, 15:12:24) 
[GCC 5.4.0 20160609]
anchoredscrollview - Anchored ScrollView Kivy widget
androidtabs - No description
androidvlc - No description
animlabel - An animated label implementation, allowing for custom transform functions
animlabel_bezier - an extension of the animlabel tool, to make a label follow a bezier path
bar - Bar widget represents the 0-100 range percentage value as a coloured rectangle. It is known as used in statistics graphs.
cefpython - CEFPython Kivy widget
circulardatetimepicker - Android-like date & time picker for Kivy
circularlayout - CircularLayout for Kivy
collider - Collides a point with a space defined by a curve.
contextmenu - No description
datetimepicker - roulette based datetime selector like in iOS and android.
ddd - A 3d view widget for kivy
desktopvideoplayer - No description
docbrowser - Browser for view documentation of Python modules
filebrowser - An advanced file browser.
filechooserthumbview - FileChooserThumbView for Kivy
gauge - Kivy Widget Gauge
geartick - A gear based Ticker for use in rotating sliders 
graph - Displays plots on a graph.
hotkeybehavior - Global HotKey behavior for a Kivy root widget
iconfonts - Simple helper functions to make easier to use icon fonts in Labels and derived widgets
inkcanvas - Gesture recognition
knob - Knob widget for Kivy.
magnet - A magnet widget for kivy garden
mapview - Mapview is a Kivy widget for displaying interactive maps.
matplotlib - Matplotlib backends using kivy
modernmenu - a stylized menu system for kivy
moretransitions - More transitions for Kivy screen manager
 Traceback (most recent call last):
   File "/home/jb/python/venv/bin/garden", line 223, in <module>
     GardenTool().main(sys.argv[1:])
   File "/home/jb/python/venv/bin/garden", line 90, in main
     if self.options.kivy and garden_kivy_dir is None:
 AttributeError: 'Namespace' object has no attribute 'kivy'
(venv) jb@jb-u16v1:~/python/meteread/bin$

**Comment by mshumilov** [comment]
It seems a duplicate to https://github.com/kivy-garden/garden/issues/23

**Comment by Inspirateur** [comment]
I got the same error and I'm not in a virtual environment,
my requirements.txt is:
Cython==0.29.6
kivy.deps.sdl2==0.1.18
kivy.deps.glew==0.1.10
ffpyplayer==4.1.0
kivy.deps.gstreamer==0.1.13
Kivy==1.10.1
requests==2.21.0
kivy-garden
obs-websocket-py==0.4
websockets==7.0
Everything installs successfully (on windows 10 with python 3.7) but when I type: garden search 
I get:
```
C:\Project\Source\CNO>python.exe C:\Users\xxx\AppData\Local\Programs\Python\Python37\Scripts\garden search
[INFO   ] [Logger      ] Record log in C:\Users\xxx\.kivy\logs\kivy_19-04-26_4.txt
[INFO   ] [Kivy        ] v1.10.1
[INFO   ] [Python      ] v3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)]
anchoredscrollview - Anchored ScrollView Kivy widget
androidtabs - No description
androidvlc - No description
animationbuilder - Easy way of writing Kivy Animations
animlabel - An animated label implementation, allowing for custom transform functions
animlabel_bezier - an extension of the animlabel tool, to make a label follow a bezier path
bar - Bar widget represents the 0-100 range percentage value as a coloured rectangle. It is known as used in statistics graphs.
cefpython - CEFPython Kivy widget
circulardatetimepicker - Android-like date & time picker for Kivy
circularlayout - CircularLayout for Kivy
collider - Collides a point with a space defined by a curve.
contactform - Kivy garden flower providing widget for sending e-mail from form on app
contextmenu - No description
datetimepicker - roulette based datetime selector like in iOS and android.
ddd - A 3d view widget for kivy
desktopvideoplayer - No description
docbrowser - Browser for view documentation of Python modules
facelock - It is a flower made for kivy-garden
filebrowser - An advanced file browser.
filechooserthumbview - FileChooserThumbView for Kivy
gauge - Kivy Widget Gauge
geartick - A gear based Ticker for use in rotating sliders
graph - Displays plots on a graph.
hotkeybehavior - Global HotKey behavior for a Kivy root widget
iconfonts - Simple helper functions to make easier to use icon fonts in Labels and derived widgets
inkcanvas - Gesture recognition
joystick - A on screen joystick for Kivy
knob - Knob widget for Kivy.
magnet - A magnet widget for kivy garden
 Traceback (most recent call last):
   File "C:\Users\xxx\AppData\Local\Programs\Python\Python37\Scripts\garden", line 223, in <module>
     GardenTool().main(sys.argv[1:])
   File "C:\Users\xxx\AppData\Local\Programs\Python\Python37\Scripts\garden", line 90, in main
     if self.options.kivy and garden_kivy_dir is None:
 AttributeError: 'Namespace' object has no attribute 'kivy'
```

**Comment by Radobilly** [comment]
On Arch, using Python 3.7.3 i'm also seemlingy having the same issue as in #24 again.

**Comment by BelGrend** [comment]
> using `pip install kivy-garden` installs a not working garden bin.
> using `pip install git+https://github.com/kivy-garden/garden@master` installs the correct one.

Still getting an error of:
ERROR: Error [WinError 2] The system cannot find the file specified while executing command git clone -q https://github.com/kivy-garden/garden
