### ISSUE TITLE
garden: command not found

### ISSUE THREAD

**Issue by maltfield** [kivy-garden/garden#36]
Following the official install instructions for kivy garden fail on Debian 10:

 * https://kivy-garden.github.io/index.html#legacygardentoolgeneralusageguidelines

## Example execution

Here is an example execution using the commands documented in the above link:

```
user@disp3499:~$ sudo apt-get install python3 python3-pip
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-pip is already the newest version (18.1-5).
python3 is already the newest version (3.7.3-1).
The following packages were automatically installed and are no longer required:
  linux-headers-4.19.0-6-amd64 linux-headers-4.19.0-6-common
  linux-image-4.19.0-6-amd64 python-daemon python-lockfile python-qubesdb
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 18 not upgraded.
user@disp3499:~$ 

user@disp3499:~$ sudo pip3 install requests
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (2.21.0)
user@disp3499:~$ 

user@disp3499:~$ pip3 install kivy-garden
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: kivy-garden in /home/user/.local/lib/python3.7/site-packages (0.1.4)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from kivy-garden) (2.21.0)
user@disp3499:~$ 

user@disp3499:~$ garden
bash: garden: command not found
user@disp3499:~$ 
```

## System info

```
user@disp3499:~$ python3 --version
Python 3.7.3
user@disp3499:~$ uname -a
Linux disp3499 4.19.132-1.pvops.qubes.x86_64 #1 SMP Tue Jul 14 03:42:21 UTC 2020 x86_64 GNU/Linux
user@disp3499:~$ cat /etc/issue
Debian GNU/Linux 10 \n \l

user@disp3499:~$ pip3 list
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Package           Version
----------------- -------------
ansible           2.7.7
apache-libcloud   2.4.0
asn1crypto        0.24.0
bcrypt            3.1.6
certifi           2018.8.24
chardet           3.0.4
croniter          0.3.24
cryptography      2.6.1
cupshelpers       1.0
distro            1.3.0
docutils          0.16
entrypoints       0.3
httplib2          0.11.3
idna              2.6
Jinja2            2.10
jmespath          0.9.4
keyring           17.1.1
keyrings.alt      3.1.1
Kivy-Garden       0.1.4
lockfile          0.12.2
MarkupSafe        1.1.0
meld              3.20.0
msgpack           0.5.6
netaddr           0.7.19
ntlm-auth         1.1.0
numpy             1.16.2
olefile           0.46
paramiko          2.4.2
Pillow            5.4.1
pip               20.2.2
psutil            5.5.1
pyasn1            0.4.2
pycairo           1.16.2
pycrypto          2.6.1
pycups            1.9.73
pycurl            7.43.0.2
Pygments          2.6.1
PyGObject         3.30.4
pykerberos        1.1.14
PyNaCl            1.3.0
PySimpleSOAP      1.16.2
pysmbc            1.0.15.6
python-apt        1.8.4.1
python-daemon     2.2.3
python-dateutil   2.7.3
python-debian     0.1.35
python-debianbts  2.8.2
pytz              2019.1
pywinrm           0.3.0
pyxdg             0.25
PyYAML            3.13
qubesagent        4.0.56
QubesDB           1.0
qubesimgconverter 4.0.30
reportbug         7.5.3-deb10u1
requests          2.21.0
requests-kerberos 0.11.0
requests-ntlm     1.1.0
salt              2018.3.4
scour             0.37
SecretStorage     2.3.1
setuptools        40.8.0
simplejson        3.16.0
six               1.12.0
tornado4          4.5.3
urllib3           1.24.1
virtualenv        15.1.0
wheel             0.32.3
xcffib            0.8.1
xmltodict         0.11.0
user@disp3499:~$ 
```

**Comment by maltfield** [comment]
I was successfully able to get this command by using the following command 

```
user@disp3499:~$ sudo pip3 install kivy-garden
Collecting kivy-garden
  Downloading https://files.pythonhosted.org/packages/7d/68/decaee596ff8168a39432eb3949fc7c0be952ebb9467806823bffc165d48/kivy-garden-0.1.4.tar.gz
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from kivy-garden) (2.21.0)
Building wheels for collected packages: kivy-garden
  Running setup.py bdist_wheel for kivy-garden ... done
  Stored in directory: /root/.cache/pip/wheels/e5/09/36/4bec048252175b6aa7ba75441cbeed8f31a0bea37abedcfed0
Successfully built kivy-garden
Installing collected packages: kivy-garden
Successfully installed kivy-garden-0.1.4
user@disp3499:~$ grden
bash: grden: command not found
user@disp3499:~$ garden
usage: garden [-h] {list,search,install,uninstall} ...

Garden command-line tool.

positional arguments:
  {list,search,install,uninstall}
    list                List all the installed garden packages
    search              Search garden package on github
    install             Install a garden package
    uninstall           Uninstall a garden package

optional arguments:
  -h, --help            show this help message and exit
Traceback (most recent call last):
  File "/usr/local/bin/garden", line 223, in <module>
    GardenTool().main(sys.argv[1:])
  File "/usr/local/bin/garden", line 90, in main
    if self.options.kivy and garden_kivy_dir is None:
AttributeError: 'Namespace' object has no attribute 'kivy'
user@disp3499:~$ 
```

Please update this page:

 * https://kivy-garden.github.io/index.html#legacygardentoolgeneralusageguidelines

By changing this line:

```
pip install kivy-garden
```

To this:

```
sudo pip install kivy-garden
```
```
```
